---
:cppcheck:
  :reports: []
  :text_artifact_filename: null
  :xml_artifact_filename: null
  :template: null
  :html_title: null
  :platform: null
  :standard: null
  :inline_suppressions: false
  :enable_checks: []
  :disable_checks: []
  :addons: []
  :includes: []
  :libraries: []
  :rules: []
  :suppressions: []
  :defines: []
  :undefines:
    - TEST
  :options: []
...
