---
:cppcheck:
  :reports: []
  :text_artifact_filename: null
  :xml_artifact_filename: null
  :template: null
  :html_title: null
  :platform: null
  :standard: null
  :check_level: null
  :inline_suppressions: false
  :enable_checks: []
  :disable_checks: []
  :addons: []
  :includes: []
  :excludes: []
  :libraries: []
  :rules: []
  :suppressions: []
  :defines: []
  :undefines:
    - TEST
  :arguments: []

:extension:
  :cppcheck: .txt

:paths:
  :cppcheck: []

:files:
  :cppcheck: []
...
